CREATE TABLE staff (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phonenumber VARCHAR(16) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);